# Generated by Django 3.1.3 on 2020-12-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='Тест', max_length=100),
        ),
    ]
