# Generated by Django 3.1.3 on 2020-12-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(to='stud_teach.Test'),
        ),
    ]
