# Generated by Django 3.1.3 on 2020-12-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0002_test_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_1',
            new_name='Вопрос 1',
        ),
    ]
