# Generated by Django 3.1.3 on 2020-12-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0003_auto_20201201_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='right',
            field=models.TextField(choices=[('1', 'Вопрос 1'), ('2', models.TextField()), ('3', models.TextField()), ('2', models.TextField())]),
        ),
    ]
