# Generated by Django 3.1.3 on 2020-12-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0003_auto_20201203_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='done_tests',
            field=models.ManyToManyField(related_name='done_tests', to='stud_teach.Test'),
        ),
        migrations.DeleteModel(
            name='PassedTest',
        ),
        migrations.AddField(
            model_name='resulttest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_teach.student'),
        ),
    ]
