# Generated by Django 3.1.3 on 2020-12-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0004_auto_20201203_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttest',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stud_teach.test'),
            preserve_default=False,
        ),
    ]
