# Generated by Django 3.1.3 on 2020-12-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0004_auto_20201201_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_2',
            new_name='1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_3',
            new_name='2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_4',
            new_name='3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='4',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Вопрос 1',
            new_name='Вопрос',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right',
        ),
        migrations.AddField(
            model_name='question',
            name='Правильный ответ',
            field=models.TextField(choices=[('1', '1'), ('2', models.TextField()), ('3', models.TextField()), ('2', models.TextField())], default='1'),
        ),
    ]
