# Generated by Django 3.1.3 on 2020-12-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0005_resulttest_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='resulttest',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='1',
            new_name='option_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='2',
            new_name='option_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='3',
            new_name='option_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='4',
            new_name='option_4',
        ),
        migrations.AlterField(
            model_name='question',
            name='Правильный ответ',
            field=models.CharField(choices=[('1', None), ('2', None), ('3', None), ('2', None)], max_length=10),
        ),
    ]
