# Generated by Django 3.1.3 on 2020-12-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0005_auto_20201201_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Правильный ответ',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('2', '4')]),
        ),
    ]
