# Generated by Django 3.1.3 on 2020-12-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_teach', '0006_auto_20201201_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Вопрос',
            new_name='text',
        ),
    ]
